### ISSUE TITLE
Friendly name for multiple entities

### ISSUE THREAD

**Issue by sbreeves1984** [Kibibit/kb-steam-card#23]
I’m using the multiple entities config within a card:

```
entities:
    - sensor.steam_
    - sensor.steam_ 
    - sensor.steam_  
    - sensor.steam_ 
friendly_name: hello
game_background: true
type: 'custom:kb-steam-card'
```
I’ve tried adding friendly names for each entity but it isn’t accepted. 

Please can we have a friendly name after each entity i.e.:
```
entities:
    - sensor.steam_
    friendly_name: hello
    - sensor.steam_ 
    friendly_name: hello
    - sensor.steam_  
    friendly_name: hello
    - sensor.steam_ 
    friendly_name: hello
game_background: true
type: 'custom:kb-steam-card'
```
